### PR TITLE
chore - increase period from 60 to 180s and treat no traffic as not breaking

### PR DESCRIPTION
**Pull request by dsaltares**

### CODE REVIEW

**Comment by amuslija** [comment]
This should solve trigger friendly alarms?

**Review by amuslija — APPROVED** [review]

**Comment by dsaltares** [comment]
We'll see if it helps!

**Review by crondinini — APPROVED** [review]
Nice! How is the period used in the calculation of errors? Is it % of errors in the last 180 seconds?

**Comment by dsaltares** [comment]
@crondinini we have this `Expression: '((requests - errors - timeouts) / requests) * 100'`. Each metric records total requests, errors and timeouts respectively, then we calculate availability as a percentage.

**Pull request merged**
